### PR TITLE
Places new module

### LINKED ISSUE #20: Put up preliminary place records
These are low priority and will not be very clean probably

### PR DESCRIPTION
**Pull request by nathangibson**
@wsalesky I'm trying to add places using the places module, not sure if I have everything correct. 

Also, I would prefer for the path to the index, browse, etc pages to be "places" rather than "geo". Is that an easy fix?

### CODE REVIEW

**Comment by wsalesky** [comment]
@nathangibson to change it from geo to places I will need to change the directory name in the app and also in the config file. I will make this change later today. And then merge them all.

**Comment by nathangibson** [comment]
Great! I was a little afraid to do that because I wasn't sure if it was coded in anywhere else.

**Comment by nathangibson** [comment]
@wsalesky While we're at it, do you want to add the configuration for the bibl module (with the address "bibl") or are there other adjustments that need to be made on that (in which case we can do it separately)?

**Comment by wsalesky** [comment]
I will add the bibl module as well. I was just starting this so it will be easy to add.

**Review by wsalesky — APPROVED** [review]

**Pull request merged**
